version: '3.4'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start.sh


  redis:
    image: redis:5.0
    ports:
      - '6379:6379'
